### ISSUE TITLE
bower assets

### ISSUE THREAD

**Issue by 3snail** [lichunqiang/yii2-swagger-demo#2]
yii set bower alias:
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower')

light\yii-swagger install swagger-ui in vendor/bower-asset

but light\yii-swagger\SwaggerUIAsset use sourcePath:
@bower/swagger-ui/dist

so it can not found assets

**Comment by lichunqiang** [comment]
See https://github.com/lichunqiang/yii2-swagger-demo/blob/master/composer.json#L50-L51
 As fxp/asset plugin can custom the install path.
